version: '3.8'

services:
  # Node.js Backend
  api-gateway:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - Python_Api_Url=http://pdf-service:5000  # Points to the python service name
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - pdf-service

  # Python PDF Handler
  pdf-service:
    build:
      context: ./Backend
      dockerfile: Dockerfile.python
    environment:
      - FLASK_ENV=production